[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "."
  functions = "netlify/functions"
  
[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"

[functions."transform"]
  timeout = 26

[functions."search"]
  timeout = 15
